import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from '@/providers/session'
import Header from './components/Header'
import Footer from './components/Footer'
import Box from '@mui/material/Box'
import { relative } from 'path'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  return (
    <html lang="en">
      <body className={inter.className}>
      <Box 
        sx={{
          position: "relative",
          minHeight: "100vh"
        }}
      >
        <NextAuthSessionProvider>
          <Header/>
            {children}
          <Footer/>
        </NextAuthSessionProvider>
      </Box>  
      </body>
    </html>
  )
}
